# **Assignment For Numpy**

Difficulty Level **Beginner**

1. Import the numpy package under the name np

In [1]:
import numpy as np

2. Create a null vector of size 10 

In [2]:
np.zeros((10))

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

3. Create a vector with values ranging from 10 to 49

In [3]:
x=np.arange(10,50)
x

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

4. Find the shape of previous array in question 3

In [4]:
x.shape

(40,)

5. Print the type of the previous array in question 3

In [5]:
x.dtype

dtype('int32')

6. Print the numpy version and the configuration


In [6]:
print(np.__version__)
np.show_config()

1.18.1
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['D:/Software/Anaconda\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'D:/Software/Anaconda\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['D:/Software/Anaconda\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'D:/S

7. Print the dimension of the array in question 3


In [7]:
x.ndim

1

8. Create a boolean array with all the True values

In [8]:
a=np.zeros((10))
a>-1

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

9. Create a two dimensional array




In [9]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

10. Create a three dimensional array



In [10]:
np.ones((3,3,3))

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

Difficulty Level **Easy**

11. Reverse a vector (first element becomes last)

In [11]:
b=np.arange(11)
c=b[::-1]
c

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

12. Create a null vector of size 10 but the fifth value which is 1 

In [12]:
d=np.zeros((10))
d[4]=1
d

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

13. Create a 3x3 identity matrix

In [13]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

14. arr = np.array([1, 2, 3, 4, 5]) 

---

 Convert the data type of the given array from int to float 

In [14]:
arr = np.array([1, 2, 3, 4, 5])
arr.astype(float)

array([1., 2., 3., 4., 5.])

15. arr1 =          np.array([[1., 2., 3.],

                    [4., 5., 6.]])  
                      
    arr2 = np.array([[0., 4., 1.],
     
                   [7., 2., 12.]])

---


Multiply arr1 with arr2


In [15]:
arr1 = np.array([[1., 2., 3.],

            [4., 5., 6.]])  
arr2 = np.array([[0., 4., 1.],

           [7., 2., 12.]])

arr1*arr2

array([[ 0.,  8.,  3.],
       [28., 10., 72.]])

16. arr1 = np.array([[1., 2., 3.],
                    [4., 5., 6.]]) 
                    
    arr2 = np.array([[0., 4., 1.], 
                    [7., 2., 12.]])


---

Make an array by comparing both the arrays provided above

In [16]:
arr1 = np.array([[1., 2., 3.],

            [4., 5., 6.]]) 
arr2 = np.array([[0., 4., 1.],

            [7., 2., 12.]])
arr1==arr2

array([[False, False, False],
       [False, False, False]])

17. Extract all odd numbers from arr with values(0-9)

In [17]:
f=np.array([0,1,2,3,4,5,6,7,8,9])
f[f%2==1]

array([1, 3, 5, 7, 9])

18. Replace all odd numbers to -1 from previous array

In [18]:
f[f%2==1]=-1
f

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

19. arr = np.arange(10)


---

Replace the values of indexes 5,6,7 and 8 to **12**

In [19]:
arr=np.arange(10)
arr[5:9]=12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12, 12,  9])

20. Create a 2d array with 1 on the border and 0 inside

In [20]:
e=np.ones((4,4))
e[1:-1,1:-1]=0
e

array([[1., 1., 1., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 1., 1., 1.]])

Difficulty Level **Medium**

21. arr2d = np.array([[1, 2, 3],

                    [4, 5, 6], 

                    [7, 8, 9]])

---

Replace the value 5 to 12

In [21]:
arr2d = np.array([[1, 2, 3],

            [4, 5, 6], 

            [7, 8, 9]])
arr2d[1,1]=12
print(arr2d)

[[ 1  2  3]
 [ 4 12  6]
 [ 7  8  9]]


22. arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

---
Convert all the values of 1st array to 64


In [22]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d[0]=64
arr3d

array([[[64, 64, 64],
        [64, 64, 64]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

23. Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

In [23]:
h=np.arange(10).reshape(5,2)
h[0,:]

array([0, 1])

24. Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it

In [24]:
h=np.arange(10).reshape(2,5)
h[1,1]

6

25. Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

In [25]:
h=np.arange(10).reshape(2,5)
h[0:2,2]

array([2, 7])

26. Create a 10x10 array with random values and find the minimum and maximum values

In [26]:
i=np.random.randn(10,10)*10
print(i)
print("-------------------")
print(np.amin(i))
print("-------------------")
print(np.amax(i))

[[  7.4465128  -10.98548827  -1.79026508  -3.2120746  -11.79518378
    3.04856835  -4.21855542 -11.73597795  -4.79242519   8.79469662]
 [  2.43876506  -9.75871458  17.26471887  -1.11726916   3.88567744
   -2.99788401  -7.42599432  14.74094481   5.24722649  -3.57570966]
 [ -8.1428301    6.42781976 -10.13819296   0.07382391   5.55095764
   10.43596396  -3.18620468  -9.94439499  -5.51281302  13.87332866]
 [ 11.75751995 -11.08845738   0.64877028  -0.22770166   8.94672442
    1.96067867   5.34645557   0.98994093  20.06375691   7.83443309]
 [ -6.01206822 -17.74954663   6.86425841  -2.37587613 -10.61107527
    9.17269627   4.90605396   5.33065736  11.03143544 -17.44933852]
 [-14.70772085   7.70814137  -8.20226784  -2.66355584   2.42235631
   -2.18605217  -7.212522   -28.45644522   6.15718373  -2.52792185]
 [  3.9722043   17.56040452  -9.68608918  -2.86048764 -13.04021623
   -5.12213499 -14.24401745 -10.80409281   3.33276658   5.84525462]
 [-10.59322445   3.09658637   2.11159171   9.29997777  

27. a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
---
Find the common items between a and b


In [27]:
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.intersect1d(a,b)

array([2, 4])

28. a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

---
Find the positions where elements of a and b match



In [28]:
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.where(a==b)

(array([1, 3, 5, 7], dtype=int64),)

29.  names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will**


In [29]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
data = np.random.randn(7, 4)
data[names!="Will"]

array([[ 0.66661832,  1.07420837, -1.01701123,  0.20280732],
       [ 0.98111611, -0.8503754 , -1.03273187, -0.15147219],
       [-0.81634559,  0.69241285,  0.63047497, -0.66410912],
       [ 0.079072  ,  0.14814093,  0.05962022,  0.10659942],
       [-0.83041624, -0.20232646, -0.12614784,  0.45556512]])

30. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will** and **Joe**



In [30]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
data = np.random.randn(7, 4)
mask=(names!="Will")&(names!="Joe")
data[mask]

array([[-0.45207157, -0.54952132, -0.10095997,  0.49199343],
       [ 0.09516651,  0.46124805,  0.17287776,  0.96379661]])

Difficulty Level **Hard**

31. Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

In [31]:
np.arange(1,16,dtype=float).reshape(5,3)

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [10., 11., 12.],
       [13., 14., 15.]])

32. Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

In [32]:
m=np.arange(1,17,dtype=float).reshape(2,2,4)
m

array([[[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.]],

       [[ 9., 10., 11., 12.],
        [13., 14., 15., 16.]]])

33. Swap axes of the array you created in Question 32

In [33]:
np.swapaxes(m,0,2)

array([[[ 1.,  9.],
        [ 5., 13.]],

       [[ 2., 10.],
        [ 6., 14.]],

       [[ 3., 11.],
        [ 7., 15.]],

       [[ 4., 12.],
        [ 8., 16.]]])

34. Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0

In [34]:
n=np.arange(0.1,10)
np.where(n<0.5,0,np.sqrt(n))

array([0.        , 1.04880885, 1.44913767, 1.76068169, 2.02484567,
       2.25831796, 2.46981781, 2.66458252, 2.84604989, 3.01662063])

35. Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays

In [35]:
arr1=np.random.randn(12)
arr2=np.random.randn(12)
np.maximum(arr1,arr2)

array([ 0.78855661,  0.29235003,  0.0362791 , -0.17847823,  0.76205184,
        0.75353886,  0.61300343, -0.21093888, -0.49414528,  1.2978746 ,
        1.15040728,  0.20139186])

36. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

---
Find the unique names and sort them out!


In [36]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
np.sort(np.unique(names))

array(['Bob', 'Joe', 'Will'], dtype='<U4')

37. a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

---
From array a remove all items present in array b



In [37]:
a = np.array([1,2,3,4,5]) 
b = np.array([5,6,7,8,9])
np.setdiff1d(a,b)


array([1, 2, 3, 4])

38.  Following is the input NumPy array delete column two and insert following new column in its place.

---
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]]) 


---

newColumn = numpy.array([[10,10,10]])


In [38]:
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]])

newColumn = np.array([[10,10,10]])
sampleArray[:,2]=newColumn
sampleArray


array([[34, 43, 10],
       [82, 22, 10],
       [53, 94, 10]])

39. x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])


---
Find the dot product of the above two matrix


In [39]:
x = np.array([[1., 2., 3.], [4., 5., 6.]]) 
y = np.array([[6., 23.], [-1, 7], [8, 9]])
x.dot(y)

array([[ 28.,  64.],
       [ 67., 181.]])

40. Generate a matrix of 20 random values and find its cumulative sum

In [40]:
k=np.random.randn(20)
l=k.cumsum()
print(l)


[ 1.81091174  2.47169303  2.79211144  1.53766229  0.31665466 -0.06677125
 -2.5417022  -2.78827895 -2.78720517 -2.30414853 -3.42244858 -3.53412431
 -4.12841659 -4.71222822 -4.22331455 -2.31341955 -1.93071216 -2.9147134
 -1.76106579 -3.36029068]
