# Numpy_Assignment_2::

## Question:1

### Convert a 1D array to a 2D array with 2 rows?

#### Desired output::

array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [1]:
import numpy as np
np.arange(10).reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

## Question:2

###  How to stack two arrays vertically?

#### Desired Output::

In [2]:
arr1=np.arange(10,dtype=int).reshape(2,5)
arr2=np.ones(10,dtype=int).reshape(2,5)
np.vstack((arr1,arr2))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

## Question:3

### How to stack two arrays horizontally?

#### Desired Output::

In [3]:
np.hstack((arr1,arr2))

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

## Question:4

### How to convert an array of arrays into a flat 1d array?

#### Desired Output::

In [4]:
arr1.flatten()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Question:5

### How to Convert higher dimension into one dimension?

#### Desired Output::

In [5]:
arr=np.arange(15).reshape(5,3)
arr
arr.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

## Question:6

### Convert one dimension to higher dimension?

#### Desired Output::

In [6]:
arr.reshape(3,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

## Question:7

### Create 5x5 an array and find the square of an array?

In [7]:
a=np.random.randn(5,5)
print(a)
print("-----------------------------------")
np.square(a)

[[ 0.81440588 -0.41858165 -0.36446451  0.01604898 -1.64747511]
 [ 0.6599254  -1.70588933 -0.40753586 -1.44250866 -0.47944942]
 [-0.50256175  0.67853491  1.36872959 -0.16948916 -0.7756061 ]
 [ 0.08868564 -0.07447565  0.75636021 -0.8769169   1.40305664]
 [ 0.6228959   1.18473971 -0.57831783  1.69743836  0.66216624]]
-----------------------------------


array([[6.63256935e-01, 1.75210598e-01, 1.32834377e-01, 2.57569747e-04,
        2.71417425e+00],
       [4.35501530e-01, 2.91005842e+00, 1.66085481e-01, 2.08083123e+00,
        2.29871748e-01],
       [2.52568313e-01, 4.60409620e-01, 1.87342068e+00, 2.87265757e-02,
        6.01564826e-01],
       [7.86514255e-03, 5.54662223e-03, 5.72080773e-01, 7.68983255e-01,
        1.96856795e+00],
       [3.87999297e-01, 1.40360817e+00, 3.34451516e-01, 2.88129699e+00,
        4.38464133e-01]])

## Question:8

### Create 5x6 an array and find the mean?

In [8]:
b=np.arange(30).reshape(5,6)
b.mean()


14.5

## Question:9

### Find the standard deviation of the previous array in Q8?

In [9]:
b.std()

8.65544144839919

## Question:10

### Find the median of the previous array in Q8?

In [10]:
np.median(b)

14.5

## Question:11

### Find the transpose of the previous array in Q8?

In [11]:
print(b)
print("------------")
b.transpose()

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]
------------


array([[ 0,  6, 12, 18, 24],
       [ 1,  7, 13, 19, 25],
       [ 2,  8, 14, 20, 26],
       [ 3,  9, 15, 21, 27],
       [ 4, 10, 16, 22, 28],
       [ 5, 11, 17, 23, 29]])

## Question:12

### Create a 4x4 an array and find the sum of diagonal elements?

In [12]:
c=np.arange(16).reshape(4,4)
c.trace()

30

## Question:13

### Find the determinant of the previous array in Q12?

In [13]:
np.linalg.det(c)

-2.9582283945787796e-30

## Question:14

### Find the 5th and 95th percentile of an array?

In [14]:
d=np.arange(1,101)
print(np.percentile(d,5))
print(np.percentile(d,95))

5.95
95.05


## Question:15

### How to find if a given array has any null values?

In [15]:
e=np.arange(11)
e.all()


False

In [16]:
#Second method
np.isnan(e).any()

False